name: kv-test

on:
  push:
    branches:
      - main
      - feature/*
      
  workflow_dispatch:
  pull_request:
    branches:
      - main

  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
permissions:
  contents: read
  pull-requests: write
  id-token: write
  issues: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: azure login
        uses: azure/login@v1
        with:
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Key vault access
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: kv-dre-test
          secrets: "*"

      - name: lisk keys
        run: |
          az keyvault key list --vault-name "kv-dre-test"

    
  other_repo:
    runs-on: ubuntu-latest
    steps:
      - name: get another repo
        uses: actions/checkout@v2
        with:
          repository: BoadDee/group31
          ref: main
    
